### ISSUE TITLE
READ ME STEPS DOESN'T INSTALL OPEN VINO TOOLKIT ON GOOGLE COLAB

### ISSUE THREAD

**Issue by Shirish-Ranoji** [alihussainia/openvino-colab#10]
![image](https://user-images.githubusercontent.com/69891605/93336800-dea4de00-f845-11ea-9ff4-b6c8e924520f.png)
Can you help me to get it resolved? I don't find open vino in the path as well.

**Comment by alihussainia** [comment]
@Shirish-Ranoji Thank you for opening this issue and notifying about the problem. It was a storage issue which has been successfully resolved. Plus, additional functionalities been included like option of choosing individual framework or all installation as well as smart input to identify wrong framework choice (i.e. selecting number option other than the available frameworks). I hope you will like the project and if it satisfies you, do not forget to give the project a star, as it is a sign of appreciation for our this honest effort. 

Best Regards and Peace,

Muhammad Ali.
Creator and Principal Developer,
OpenDevLibrary Project.

**Comment by waghts95** [comment]
I am having same issue.
python3: can't open file '/opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/downloader.py': [Errno 2] No such file or directory

There is no intel folder in /opt
