### ISSUE TITLE
Reorder the step for drive in readme.md which is must Required for newcomers 

### ISSUE THREAD

**Issue by ahkhalwai** [alihussainia/openvino-colab#6]
For newbebies it's good learn how it's works

Step 1) How to create a folder 
Step 2) How to install l_openvino_toolkit_p_2020.1.023.tgz to drive
step 3) then how to use this tgz file in colab

**Comment by alihussainia** [comment]
Dear, @ahkhalwai.

First of all, thank you so much for taking an interest in the project. Coming to the issues;
Our prime focus is on beginners, my dear friend. And that is why we removed the explicit folder creation, downloading Gbs of OpenVINO installer file as well as waiting for many minutes in uploading that huge installer file. The .py file is basically, an api, which install everything without using many irrelevant steps to do a task that can be done in just few steps.

**Comment by alihussainia** [comment]
Furthermore, a pro tip for beginners who are willing to learn the OpenVINO installation in detail, please I would highly recommend to read the .py file code and understand the flow.
